apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: thisabdu/api:latest
        ports:
          - containerPort: 50051
        env:
          - name: DATABASE_URL
            value: "postgres://stockuser:stockpass@postgres-service:5432/stockdb?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
