apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: thisabdu/producer:latest
        env:
        - name: PULSAR_URL
          value: "pulsar://pulsar-service:6650"